### ISSUE TITLE
Import video from Gallery

### ISSUE THREAD

**Issue by gbdomubpkm** [pavelprosto94/uvideo#11]
I don't remember if it worked before but we can't currently import a video from Gallery

Edit 07/04 : yes it was possible on previous update
(seen on Nexus 5)

**Comment by pavelprosto94** [comment]
The video player works correctly with the file manager, there are problems with the gallery. Content Hub does not always work correctly and this is already the competence of uBport.
I tried to receive files directly, but this method was forbidden to me.
