### ISSUE TITLE
''Deleted'' video always in the Cache

### ISSUE THREAD

**Issue by gbdomubpkm** [pavelprosto94/uvideo#12]
Delete a video with the dustbin only 'delele' the video from the playlist. But the video is always in hblncoming  in your Cache folder.
As a result, if we add the same video to the playlist, the same video is two times in the cache.

**Comment by pavelprosto94** [comment]
The cache contains only links to video files. This is a feature of the Content Hub - I wrote about this to the Ubuntu developers, maybe someday they will add the ability to remove these links by the program itself.

**Comment by gbdomubpkm** [comment]
Sorry to sound insistant, it is only for a well understanding, i am not a developer..
In my example, what you say is that, currently, it's a normal thing to have always a 'link' of 159 MB after deleted the file of the playlist ?
![screenshot20210416_085142890](https://user-images.githubusercontent.com/50362604/114985677-5d710080-9e93-11eb-9d71-260187b4c977.png)
And if i delete (using dustbin)  and add for example 3 times the same file, it is a normal operation that this file will stay 3 times (455 MB) in the cache like this (UTT) ? 
![screenshot20210416_105152185](https://user-images.githubusercontent.com/50362604/115001054-a29d2e80-9ea3-11eb-9eab-cf4ebc79514a.png)
