### ISSUE TITLE
name of your app

### ISSUE THREAD

**Issue by gbdomubpkm** [pavelprosto94/uvideo#14]
shouldn't the name of your app in the OpenStore be '**uvideo**' and not 'video player' ? 

There is another video player and is name is UTmedia
![screenshot20210415_062620073](https://user-images.githubusercontent.com/50362604/114814145-def16180-9db3-11eb-934d-2fe2cb9216ab.png)

**Comment by pavelprosto94** [comment]
uVideo stands for "Video Player for Ubuntu Toch"
This program has no name, it's just a video player =)

**Comment by gbdomubpkm** [comment]
ok.
