### ISSUE TITLE
3gp   Codec

### ISSUE THREAD

**Issue by gbdomubpkm** [pavelprosto94/uvideo#8]
Could you add  3gp   codec ?
Would be usefull as a lot of phone videos use this codec.
Thanks.

**Comment by pavelprosto94** [comment]
Unfortunately this is not possible = (The application works exclusively on Chromium codecs, where the 3gp format is not provided.
But I have successfully compiled the FFMPEG library so I will soon release a video converter for Ubuntu Touch.

**Comment by gbdomubpkm** [comment]
A video converter for UT ? It is more than a workaround  🙂 !
I wouldn't have dared to ask or imagine that !
Very impatient and thanks in advance 👍

**Comment by gbdomubpkm** [comment]
Hello. Did you do a .click of the video converter to try ?

**Comment by gbdomubpkm** [comment]
Hello.
Is the FFMPEG project for UT dead ?
